[phases.setup]
nixPkgs = [
    "php81",
    "php81Extensions.pdo_mysql",
    "php81Extensions.mbstring",
    "php81Extensions.exif",
    "php81Extensions.pcntl",
    "php81Extensions.bcmath",
    "php81Extensions.gd",
    "php81Extensions.intl",
    "php81Extensions.zip",
    "composer",
    "nodejs",
    "npm",
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "NODE_OPTIONS='--openssl-legacy-provider' npm run production",
]

[phases.build]
cmds = [
    "php artisan key:generate --no-interaction",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NODE_OPTIONS = "--openssl-legacy-provider"
